name: rypt
description: A workout tracking application.
repository: https://github.com/tytydraco/rypt
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.6
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  flutter_login: ^4.0.0
  provider: ^6.0.3
  shared_objects: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any

flutter:
  uses-material-design: true
